### ISSUE TITLE
Mobs evading

### ISSUE THREAD

**Issue by Dreask** [talamortis/server#12]
Description of the Issue:
When doing the Grimtotem quests at Darkcloud Pinnacle in Thousand Needles, when you aggro mobs and go on the wooden bridges they will evade, instead of following you. Also when using charge on mob on the bridge, you fall through it.

QuestID/ BossID:

Instance:
Thousand Needles - Darkcloud Pinnacle
What should happen:
You should be able to fight them on the bridge

Faction: Horde/Alliance
Horde, orc warrior.

How to repoduce:

**Comment by talamortis** [comment]
This is a Mob map issue.
